package jetbreins.mps.DSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Actuator = 0;
  public static final int ActuatorType = 1;
  public static final int ActuatorTypeReference = 2;
  public static final int Device = 3;
  public static final int IoTSystem = 4;
  public static final int Network = 5;
  public static final int NetworkReference = 6;
  public static final int Sensor = 7;
  public static final int SensorType = 8;
  public static final int sensorTypeReference = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L);
    builder.put(0x5061f666854d687aL, Actuator);
    builder.put(0x5061f666854d68a0L, ActuatorType);
    builder.put(0x5061f666854e2199L, ActuatorTypeReference);
    builder.put(0x5061f6668548b6bfL, Device);
    builder.put(0x5061f666855046a8L, IoTSystem);
    builder.put(0x5061f6668548b6c6L, Network);
    builder.put(0x5061f6668549a91cL, NetworkReference);
    builder.put(0x5061f666854a8bfcL, Sensor);
    builder.put(0x5061f666854a8bfdL, SensorType);
    builder.put(0x5061f666854a9025L, sensorTypeReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
