package jetbreins.mps.DSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptActuatorType = createDescriptorForActuatorType();
  /*package*/ final ConceptDescriptor myConceptActuatorTypeReference = createDescriptorForActuatorTypeReference();
  /*package*/ final ConceptDescriptor myConceptDevice = createDescriptorForDevice();
  /*package*/ final ConceptDescriptor myConceptIoTSystem = createDescriptorForIoTSystem();
  /*package*/ final ConceptDescriptor myConceptNetwork = createDescriptorForNetwork();
  /*package*/ final ConceptDescriptor myConceptNetworkReference = createDescriptorForNetworkReference();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  /*package*/ final ConceptDescriptor myConceptSensorType = createDescriptorForSensorType();
  /*package*/ final ConceptDescriptor myConceptsensorTypeReference = createDescriptorForsensorTypeReference();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActuator, myConceptActuatorType, myConceptActuatorTypeReference, myConceptDevice, myConceptIoTSystem, myConceptNetwork, myConceptNetworkReference, myConceptSensor, myConceptSensorType, myConceptsensorTypeReference);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.ActuatorType:
        return myConceptActuatorType;
      case LanguageConceptSwitch.ActuatorTypeReference:
        return myConceptActuatorTypeReference;
      case LanguageConceptSwitch.Device:
        return myConceptDevice;
      case LanguageConceptSwitch.IoTSystem:
        return myConceptIoTSystem;
      case LanguageConceptSwitch.Network:
        return myConceptNetwork;
      case LanguageConceptSwitch.NetworkReference:
        return myConceptNetworkReference;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      case LanguageConceptSwitch.SensorType:
        return myConceptSensorType;
      case LanguageConceptSwitch.sensorTypeReference:
        return myConceptsensorTypeReference;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "Actuator", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854d687aL);
    b.class_(false, false, false);
    b.super_("jetbreins.mps.DSL.structure.Device", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668548b6bfL);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958708346");
    b.version(2);
    b.aggregate("actuatorType", 0x5061f666854e21eaL).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854e2199L).optional(false).ordered(true).multiple(false).origin("5792181515958755818").done();
    b.aggregate("typeNetwork", 0x5061f6668549a8faL).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668549a91cL).optional(false).ordered(true).multiple(false).origin("5792181515958462714").done();
    b.alias("actuator");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActuatorType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "ActuatorType", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854d68a0L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958708384");
    b.version(2);
    b.alias("actuatorType");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForActuatorTypeReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "ActuatorTypeReference", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854e2199L);
    b.class_(false, false, false);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958755737");
    b.version(2);
    b.associate("typeActuator", 0x5061f666854e219aL).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854d68a0L).optional(false).origin("5792181515958755738").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDevice() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "Device", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668548b6bfL);
    b.class_(false, true, false);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958400703");
    b.version(2);
    b.property("value", 0x5061f6668548b6c4L).type(PrimitiveTypeId.INTEGER).origin("5792181515958400708").done();
    b.property("name", 0x5061f66685577018L).type(PrimitiveTypeId.STRING).origin("5792181515959365656").done();
    b.alias("device");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIoTSystem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "IoTSystem", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666855046a8L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958896296");
    b.version(2);
    b.aggregate("devices", 0x5061f66685531809L).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668548b6bfL).optional(true).ordered(true).multiple(true).origin("5792181515959080969").done();
    b.alias("IoTSystem");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNetwork() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "Network", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668548b6c6L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958400710");
    b.version(2);
    b.alias("typeNetwork");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNetworkReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "NetworkReference", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668549a91cL);
    b.class_(false, false, false);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958462748");
    b.version(2);
    b.associate("typeNetwork", 0x5061f6668549a91dL).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668548b6c6L).optional(false).origin("5792181515958462749").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "Sensor", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854a8bfcL);
    b.class_(false, false, false);
    b.super_("jetbreins.mps.DSL.structure.Device", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668548b6bfL);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958520828");
    b.version(2);
    b.property("port", 0x2f883a09c49b06d4L).type(PrimitiveTypeId.INTEGER).origin("3425051330242873044").done();
    b.aggregate("sensorType", 0x5061f666854a9045L).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854a9025L).optional(false).ordered(true).multiple(false).origin("5792181515958521925").done();
    b.aggregate("typeNetwork", 0x4452763298c308f9L).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f6668549a91cL).optional(false).ordered(true).multiple(false).origin("4923127302352734457").done();
    b.alias("sencor");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensorType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "SensorType", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854a8bfdL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958520829");
    b.version(2);
    b.alias("sensorType");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForsensorTypeReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbreins.mps.DSL", "sensorTypeReference", 0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854a9025L);
    b.class_(false, false, false);
    b.origin("r:f45814cf-bd6a-4704-b7ff-1aa95a3691d7(jetbreins.mps.DSL.structure)/5792181515958521893");
    b.version(2);
    b.associate("sensorType", 0x5061f666854a9026L).target(0xfeb17c0829d94491L, 0x8d09f7c77293d2b9L, 0x5061f666854a8bfdL).optional(false).origin("5792181515958521894").done();
    return b.create();
  }
}
